# Generated by Django 3.2 on 2022-05-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, verbose_name='类别')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('press', models.CharField(max_length=16, verbose_name='出版社')),
                ('year', models.IntegerField(verbose_name='出版年份')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('total', models.IntegerField(verbose_name='总藏书量')),
                ('inventory', models.IntegerField(verbose_name='当前库存')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('institution', models.CharField(max_length=16, verbose_name='机构')),
                ('position', models.SmallIntegerField(choices=[(1, '学生'), (2, '教职工')], verbose_name='身份')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField(verbose_name='借出时间')),
                ('return_date', models.DateField(verbose_name='还书时间')),
                ('appointed', models.BooleanField(verbose_name='已被预约')),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_func.admin', verbose_name='管理员id')),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_func.book', verbose_name='书本id')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_func.card', verbose_name='借书证id')),
            ],
        ),
    ]
