# Generated by Django 3.2 on 2022-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_func', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=16, verbose_name='书名'),
        ),
    ]
