# Generated by Django 3.2 on 2022-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_func', '0004_auto_20220514_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='已归还'),
        ),
    ]
