# Generated by Django 3.2 on 2022-05-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_func', '0005_record_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_func.book', verbose_name='书本id'),
        ),
    ]
